version: '3.7'

services:
  wheathercheck:
    image: brunobevilaquaa/weather-check
    build: .
    container_name: weathercheck
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}